{% set version = "3.1.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-oompadata
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/oompaData_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/oompaData/oompaData_{{ version }}.tar.gz
  sha256: aeb932f75d3de2101d2e1b387fe76677f2d38d4819710320c0e3df07df3ab73d

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('oompaData')"           # [not win]
    - "\"%R%\" -e \"library('oompaData')\""  # [win]

about:
  home: http://oompa.r-forge.r-project.org/
  license: Apache-2.0
  license_file: LICENSE-2.0.txt
  summary: This is a data-only package to provide example data for other packages that are part of the "Object-Oriented Microrray and Proteomics Analysis" suite of packages. These are described in more detail at the package URL.
  license_family: APACHE

extra:
  recipe-maintainers:
    - conda-forge/r
    - bensellak
