appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: J4Byt6uW0Tc+HdNOtx/+zBBeWU9qUyE96OlEt3nc7D3UtMSG6BcUO2nV8ZsmFX5ezxSQcWjAPOuikgd6l8lnjszNuVwewyjvgjh8cV63tzx0jY/MbQ0BIjc7d2XqLtER6re11EbpfIlqxJMY+nBeauRlYvrUBLMrbK7oYx/rIx10h/tVU/wRncWWpIHVJ9kuVnetURaiUXUfrcJ4Ip7tMEYdCFFdEapjTxsMaYntiDlIycbkrPAghcbejX4vDjcehvCvp521vEUMK0CSWl5A2zx7+B6Rnm5Kj/oB6LxshyBeZ1Lxm+MFoASDNMuAnh3SNMYEhFCzJiqpqG1feVBS6F8vLgL+kwBHRt3nNsJD0/3y5l2MQ8+OSnRwDy59F070vO+sM4rEtMKtYk3ohCv9NaPunT1RROADLluKrIO91b1EpsZ1wPNgnOI8qcMIL4DRcNDhOBcG9UisEMYO/fQ5MhXjzY6Pw1kvwuFn5IBTL52a1OEn1u9LBN4+BGHeElADP9Sh5nABqA2krfLD4oUsgxytLNfaAGoiAtZyMlqsld9h8UvmDXgn5WROolHOZg8aJUBt9kixmZ21GC0n+OZr2Pa/i0T1mw/p2s0OBCPuqEqszaSWm0vHTclORJY6zE5dE/2h17CcfVkGSvFpQbKejX48gEvWlAawtEwFDJhvrxg=}
